# Generated by Django 5.0.6 on 2024-06-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('date', models.DateField(auto_created=True)),
                ('item', models.CharField(max_length=300)),
                ('subitem', models.CharField(max_length=300)),
            ],
        ),
    ]
